package project_euler

/**
 * Problem 44:
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk,
 * for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 *
 * 問題 44:
 * 五角数は Pn = n(3n-1)/2 で生成される. 最初の10項は
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * である.
 *
 * P4 + P7 = 22 + 70 = 92 = P8 である. しかし差 70 - 22 = 48 は五角数ではない.
 *
 * 五角数のペア Pj と Pk について, 差と和が五角数になるものを考える. 差を D = |Pk - Pj| と書く. 差 D の最小値を求めよ.
 */
object P044 {
  def solve: Long = ???
}
